name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Set to the Node.js version you are using

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn tsc

      - name: Deploy to DigitalOcean VM
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }} # Add your SSH password to GitHub secrets
          SSH_HOST: ${{ secrets.SSH_HOST }} # Add your SSH host to GitHub secrets
          SSH_USER: ${{ secrets.SSH_USER }} # Add your SSH user to GitHub secrets
        run: |
          # Install sshpass to handle password authentication
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Connect to the DigitalOcean VM and run deployment commands
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            cd ~/backend
            git pull origin main
            yarn install
            yarn tsc
            pm2 restart 0
          EOF
