name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn tsc

      - name: Deploy to DigitalOcean VM
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          PORT: ${{ secrets.PORT }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          SECRET: ${{ secrets.SECRET }}
          GUPSHUP_API_KEY: ${{ secrets.GUPSHUP_API_KEY }}
          GUPSHUP_API: ${{ secrets.GUPSHUP_API }}
          WHATSAPP_SOURCE_NUMBER: ${{ secrets.WHATSAPP_SOURCE_NUMBER }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          INSTAGRAM_API_KEY: ${{ secrets.INSTAGRAM_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          LINKEDIN_API_KEY: ${{ secrets.LINKEDIN_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
          ZOHO_CLIENT_SECRET: ${{ secrets.ZOHO_CLIENT_SECRET }}
          ZOHO_CLIENT_ID: ${{ secrets.ZOHO_CLIENT_ID }}
          ZOHO_REFRESH_TOKEN: ${{ secrets.ZOHO_REFRESH_TOKEN }}
        run: |
          # Install sshpass to handle password authentication
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Decode Base64 private key
          PRIVATE_KEY=$(echo "$PRIVATE_KEY" | base64 -d)

          # Create or update the .env file on the remote server
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            echo "DB_HOST=$DB_HOST" > backend/.env
            echo "DB_USER=$DB_USER" >> backend/.env
            echo "DB_NAME=$DB_NAME" >> backend/.env
            echo "DB_PASS=$DB_PASS" >> backend/.env
            echo "DB_PORT=$DB_PORT" >> backend/.env
            echo "PORT=$PORT" >> backend/.env
            echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> backend/.env
            echo "FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL" >> backend/.env
            echo "PRIVATE_KEY=\"$PRIVATE_KEY\"" >> backend/.env
            echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> backend/.env
            echo "MAIL_PORT=$MAIL_PORT" >> backend/.env
            echo "MAIL_HOST=$MAIL_HOST" >> backend/.env
            echo "MAIL_USER=$MAIL_USER" >> backend/.env
            echo "MAIL_PASS=$MAIL_PASS" >> backend/.env
            echo "SECRET=$SECRET" >> backend/.env
            echo "GUPSHUP_API_KEY=$GUPSHUP_API_KEY" >> backend/.env
            echo "GUPSHUP_API=$GUPSHUP_API" >> backend/.env
            echo "WHATSAPP_SOURCE_NUMBER=$WHATSAPP_SOURCE_NUMBER" >> backend/.env
            echo "FRONTEND_URL=$FRONTEND_URL" >> backend/.env
            echo "INSTAGRAM_API_KEY=$INSTAGRAM_API_KEY" >> backend/.env
            echo "YOUTUBE_API_KEY=$YOUTUBE_API_KEY" >> backend/.env
            echo "LINKEDIN_API_KEY=$LINKEDIN_API_KEY" >> backend/.env
            echo "TWITTER_API_KEY=$TWITTER_API_KEY" >> backend/.env
            echo "FB_STORAGE_BUCKET=$FB_STORAGE_BUCKET" >> backend/.env
            echo "RAZORPAY_KEY_ID=$RAZORPAY_KEY_ID" >> backend/.env
            echo "RAZORPAY_KEY_SECRET=$RAZORPAY_KEY_SECRET" >> backend/.env
            echo "RAZORPAY_ACCOUNT_NUMBER=$RAZORPAY_ACCOUNT_NUMBER" >> backend/.env
            echo "RAZORPAY_WEBHOOK_SECRET=$RAZORPAY_WEBHOOK_SECRET" >> backend/.env
            echo "ZOHO_CLIENT_SECRET=$ZOHO_CLIENT_SECRET" >> backend/.env
            echo "ZOHO_CLIENT_ID=$ZOHO_CLIENT_ID" >> backend/.env
            echo "ZOHO_REFRESH_TOKEN=$ZOHO_REFRESH_TOKEN" >> backend/.env
            pm2 stop digiwhistle-api
            cd backend
            mkdir reports
            git pull origin main
            yarn install
            yarn tsc
            pm2 start dist/index.js --name digiwhistle-api
          EOF
